name: mlops-exp-6
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run:
          # Enter instructions to run here
          pip install -r requirements.txt
          python train.py
